/**
 * 补抓第一轮 MISS 的图标（已知路径 + 多策略）
 * 用法: node scripts/patch-icons.mjs
 */
import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))

// 已知的图标直接路径
const KNOWN_ICONS = {
  'ChatGPT':     'https://cdn.oaistatic.com/assets/favicon-o20kmmos.svg',
  'Gemini':      'https://www.gstatic.com/lamda/images/gemini_sparkle_v002_d4735304ff6292a690345.svg',
  'Copilot':     'https://copilot.microsoft.com/favicon.ico',
  'Perplexity':  'https://www.perplexity.ai/favicon.ico',
  'Grok':        'https://grok.x.ai/favicon.ico',
  'Poe':         'https://poe.com/favicon.ico',
  'Meta AI':     'https://ai.meta.com/favicon.ico',
  'Blackbox AI': 'https://www.blackbox.ai/favicon.ico',
  'Writesonic':  'https://writesonic.com/favicon.ico',
  'Effidit':     'https://effidit.qq.com/favicon.ico',
  'Midjourney':  'https://www.midjourney.com/favicon.ico',
  'Leonardo AI': 'https://leonardo.ai/favicon.ico',
  'Playground':  'https://playgroundai.com/favicon.ico',
  'Ideogram':    'https://ideogram.ai/favicon.ico',
  'Pika':        'https://pika.art/favicon.ico',
  'HeyGen':      'https://www.heygen.com/favicon.ico',
  'ElevenLabs':  'https://elevenlabs.io/favicon.ico',
  'Descript':    'https://www.descript.com/favicon.ico',
  'Suno':        'https://suno.ai/favicon.ico',
  'Fish Audio':  'https://fish.audio/favicon.ico',
  'Canva':       'https://static.canva.com/static/images/favicon-1.ico',
  'Gamma':       'https://gamma.app/favicon.ico',
  'Tome':        'https://tome.app/favicon.ico',
}

async function tryFetch(url) {
  const res = await fetch(url, {
    signal: AbortSignal.timeout(15000),
    headers: {
      'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36',
      'Accept': 'image/webp,image/apng,image/*,*/*;q=0.8',
    },
    redirect: 'follow',
  })
  if (!res.ok) return null
  const buf = Buffer.from(await res.arrayBuffer())
  if (buf.length < 50) return null
  const ct = res.headers.get('content-type') || 'image/x-icon'
  const mime = ct.split(';')[0].trim()
  return `data:${mime};base64,${buf.toString('base64')}`
}

async function main() {
  const dataPath = path.resolve(__dirname, '../src/data/ai-sites.js')
  const { AI_SITES, AI_CATEGORIES } = await import('file://' + dataPath.replace(/\\/g, '/'))

  let patched = 0
  for (const site of AI_SITES) {
    if (site.icon_url) continue
    const knownUrl = KNOWN_ICONS[site.name]
    if (!knownUrl) continue

    process.stdout.write(`Patching ${site.name}...`)
    try {
      const result = await tryFetch(knownUrl)
      if (result) {
        site.icon_url = result
        patched++
        console.log(' OK')
      } else {
        // fallback: Google
        const hostname = new URL(site.url).hostname
        const r = await tryFetch(`https://www.google.com/s2/favicons?domain=${hostname}&sz=128`)
        if (r) {
          site.icon_url = r
          patched++
          console.log(' OK (google)')
        } else {
          console.log(' MISS')
        }
      }
    } catch (e) {
      console.log(' ERROR: ' + e.message)
    }
  }

  console.log(`\nPatched ${patched} icons`)

  const output = `// Auto-generated by scripts/fetch-ai-icons.mjs — DO NOT EDIT
export const AI_CATEGORIES = ${JSON.stringify(AI_CATEGORIES, null, 2)}

export const AI_SITES = ${JSON.stringify(AI_SITES, null, 2)}
`
  fs.writeFileSync(dataPath, output, 'utf-8')
  console.log('Updated ' + dataPath)

  const still = AI_SITES.filter(s => !s.icon_url)
  if (still.length) {
    console.log(`Still missing (${still.length}):`)
    still.forEach(s => console.log('  ' + s.name))
  }
}

main().catch(console.error)
